/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gramautoteoria.Vista;

import gramautoteoria.Modelo.Automata;
import gramautoteoria.Modelo.Gramatica;
import gramautoteoria.Vista.GramaticaVista;
import static gramautoteoria.Vista.GramaticaVista.gramaticaTexto;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cristian.torresa
 */
public class AutomataVista extends javax.swing.JFrame {
    
    String gramaticaTexto = GramaticaVista.gramaticaTexto.getText();
    Gramatica gramaticaObjeto = new Gramatica();
    Automata automata = new Automata();
    private JFileChooser seleccionar = new JFileChooser();
    private File archivo;
    private FileInputStream entrada;
    private FileOutputStream salida;

    /**
     * Creates new form NewJFrame
     */
    public AutomataVista() {
        initComponents();
        
        gramaticaTexto = gramaticaTexto.replace(" ", "");
        gramaticaTexto = gramaticaTexto.replace("\r", "");
        gramaticaObjeto.generarGramaticaFichero(gramaticaTexto);
        gramaticaObjeto = gramaticaObjeto.convertirLinealDerecha();
        automata = gramaticaObjeto.gramaticaAAutomata();
        DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
        automata.imprimirAutomataTabla(modelo);
        
        
        
        
    }
    
    public String abrirArchivo(File Archivo) {
        String documento = "";
        try {
            entrada = new FileInputStream(archivo);
            int ascci;
            while ((ascci = entrada.read()) != -1) {
                char caracter = (char) ascci;
                documento += caracter;
            }
        } catch (Exception e) {

        }

        return documento;

    }
    
    public String guardarArchivo(File archivo, String documento){
        String mensaje = null;
        try{
            salida = new FileOutputStream(archivo);
            byte [] bytxt = documento.getBytes();
            salida.write(bytxt);
            mensaje = "Archivo guardado";
        } catch (Exception e){
            
        } return mensaje;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultadoTexto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        evaluarBoton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        deterministicoBoton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        guardarAutomataBoton = new javax.swing.JButton();
        leerBoton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(resultadoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 680, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Evaluar hilera");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        evaluarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gramautoteoria/Img/FondoBtnSombra2.png"))); // NOI18N
        evaluarBoton.setText("Evaluar");
        evaluarBoton.setBorderPainted(false);
        evaluarBoton.setContentAreaFilled(false);
        evaluarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        evaluarBoton.setDefaultCapable(false);
        evaluarBoton.setFocusPainted(false);
        evaluarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        evaluarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaluarBotonActionPerformed(evt);
            }
        });
        getContentPane().add(evaluarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, -1, 60));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gramautoteoria/Img/FondoBtnSombra.png"))); // NOI18N
        jButton2.setText("Eliminar Estados Extraños");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        deterministicoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gramautoteoria/Img/FondoBtnSombra.png"))); // NOI18N
        deterministicoBoton.setText("¿Es determinístico?");
        deterministicoBoton.setBorderPainted(false);
        deterministicoBoton.setContentAreaFilled(false);
        deterministicoBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deterministicoBoton.setDefaultCapable(false);
        deterministicoBoton.setFocusPainted(false);
        deterministicoBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deterministicoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deterministicoBotonActionPerformed(evt);
            }
        });
        getContentPane().add(deterministicoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 155, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gramautoteoria/Img/FondoBtnSombra.png"))); // NOI18N
        jButton4.setText("Eliminar Estados Equivalentes");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, -1, -1));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Tabla);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 770, 302));

        guardarAutomataBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gramautoteoria/Img/FondoBtnSombra2.png"))); // NOI18N
        guardarAutomataBoton.setText("Guardar ");
        guardarAutomataBoton.setBorderPainted(false);
        guardarAutomataBoton.setContentAreaFilled(false);
        guardarAutomataBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarAutomataBoton.setFocusPainted(false);
        guardarAutomataBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardarAutomataBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarAutomataBotonActionPerformed(evt);
            }
        });
        getContentPane().add(guardarAutomataBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 130, -1));

        leerBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gramautoteoria/Img/FondoBtnSombra2.png"))); // NOI18N
        leerBoton.setText("Leer ");
        leerBoton.setBorderPainted(false);
        leerBoton.setContentAreaFilled(false);
        leerBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leerBoton.setDefaultCapable(false);
        leerBoton.setFocusPainted(false);
        leerBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        leerBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerBotonActionPerformed(evt);
            }
        });
        getContentPane().add(leerBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 130, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("X");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 50, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gramautoteoria/Img/Título.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gramautoteoria/Img/Fondo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void evaluarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaluarBotonActionPerformed
        String hilera = resultadoTexto.getText();
        if(automata.evaluarHilera(hilera)){
            JOptionPane.showMessageDialog(null, "La hilera es válida");
        }
        else{
            JOptionPane.showMessageDialog(null, "La hilera no es válida");
        }
    }//GEN-LAST:event_evaluarBotonActionPerformed

    private void guardarAutomataBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarAutomataBotonActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
        if (seleccionar.showDialog(null, "Guardar") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionar.getSelectedFile();            
            if (archivo.getName().endsWith("txt")) {
                String Documento = automata.imprimirAutomata();
                String mensaje = this.guardarArchivo(archivo, Documento);
                if (mensaje != null) {
                    JOptionPane.showMessageDialog(null, mensaje);
                } else {
                    JOptionPane.showMessageDialog(null, "No se ha selecciona un archivo txt");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Archivo debe terminar con .txt");
            }
        }
    }//GEN-LAST:event_guardarAutomataBotonActionPerformed

    private void deterministicoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deterministicoBotonActionPerformed
        if(automata.esDeterministico()){
            resultadoTexto.setText("El automata es deterministico");
        }
        else{
            resultadoTexto.setText("El automata no es deterministico");
        }
    }//GEN-LAST:event_deterministicoBotonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Automata nuevo = automata.eliminarEstadosExtraños();
        automata = nuevo;
        DefaultTableModel modelo = new DefaultTableModel();
                    Tabla.setModel(modelo);
        automata.imprimirAutomataTabla(modelo);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void leerBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerBotonActionPerformed
        if(seleccionar.showDialog(null, "Abrir")==JFileChooser.APPROVE_OPTION){
            archivo = seleccionar.getSelectedFile();
            if(archivo.canRead()){
                if(archivo.getName().endsWith("txt")){
                    String documento = this.abrirArchivo(archivo);
                    
                    documento = documento.replace(" ", "");
                    documento = documento.replace("\r", "");
                    DefaultTableModel modelo = new DefaultTableModel();
                    Tabla.setModel(modelo);
                    automata = automata.generarAutomataFichero(documento);
                    automata.imprimirAutomataTabla(modelo);
                    
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "No se ha seleccionado un archivo txt");
                }
            }
        }
    }//GEN-LAST:event_leerBotonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try { automata.eliminarEstadosEquivalentes();
        DefaultTableModel modelo = new DefaultTableModel();
        Tabla.setModel(modelo);
        automata.imprimirAutomataTabla(modelo);  
       }catch(NumberFormatException e) {
           resultadoTexto.setText("El automata no tiene estados equivalentes");
       }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutomataVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutomataVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutomataVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutomataVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutomataVista().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton deterministicoBoton;
    private javax.swing.JButton evaluarBoton;
    private javax.swing.JButton guardarAutomataBoton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton leerBoton;
    private javax.swing.JTextField resultadoTexto;
    // End of variables declaration//GEN-END:variables
}
