/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gramautoteoria.Vista;

import gramautoteoria.Modelo.Automata;
import gramautoteoria.Modelo.Gramatica;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class GramaticaVista extends javax.swing.JFrame {
    
    
    private Gramatica gramatica = new Gramatica();
    private JFileChooser seleccionar = new JFileChooser();
    private File archivo;
    private FileInputStream entrada;
    private FileOutputStream salida;

    /**
     * Creates new form Principal
     */
    public GramaticaVista() {
        initComponents();
    }
    
    public String abrirArchivo(File Archivo) {
        String documento = "";
        try {
            entrada = new FileInputStream(archivo);
            int ascci;
            while ((ascci = entrada.read()) != -1) {
                char caracter = (char) ascci;
                documento += caracter;
            }
        } catch (Exception e) {

        }

        return documento;

    }
    
    public String guardarArchivo(File archivo, String documento){
        String mensaje = null;
        try{
            salida = new FileOutputStream(archivo);
            byte [] bytxt = documento.getBytes();
            salida.write(bytxt);
            mensaje = "Archivo guardado";
        } catch (Exception e){
            
        } return mensaje;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        guardarBoton = new javax.swing.JButton();
        leerBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        derechoTexto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        izquierdoTexto = new javax.swing.JTextField();
        ingresarBotón = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        esSimplificableBoton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        NTTexto = new javax.swing.JTextPane();
        conjuntosBoton = new javax.swing.JButton();
        simplificarBoton = new javax.swing.JButton();
        regularBoton = new javax.swing.JButton();
        editarBoton = new javax.swing.JButton();
        eliminarBoton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        posicionTexto = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        cambioTexto = new javax.swing.JTextPane();
        izquierdaCheck = new javax.swing.JCheckBox();
        derechaCheck = new javax.swing.JCheckBox();
        automataBoton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        guardarBoton.setText("Guardar archivo");
        guardarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBotonActionPerformed(evt);
            }
        });

        leerBoton.setText("Leer archivo");
        leerBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerBotonActionPerformed(evt);
            }
        });

        jLabel1.setText("Lado derecho");

        jLabel2.setText("Lado izquierdo");

        ingresarBotón.setText("Ingresar producción");
        ingresarBotón.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarBotónActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(gramaticaTexto);

        esSimplificableBoton.setText("¿Es simplificable?");
        esSimplificableBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esSimplificableBotonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(NTTexto);

        conjuntosBoton.setText("Conjuntos");
        conjuntosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conjuntosBotonActionPerformed(evt);
            }
        });

        simplificarBoton.setText("Simplificar");
        simplificarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simplificarBotonActionPerformed(evt);
            }
        });

        regularBoton.setText("¿Es regular?");
        regularBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regularBotonActionPerformed(evt);
            }
        });

        editarBoton.setText("Editar");
        editarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBotonActionPerformed(evt);
            }
        });

        eliminarBoton.setText("Eliminar");
        eliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBotonActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(posicionTexto);

        jScrollPane4.setViewportView(cambioTexto);

        izquierdaCheck.setText("Izquierda");
        izquierdaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izquierdaCheckActionPerformed(evt);
            }
        });

        derechaCheck.setText("Derecha");
        derechaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derechaCheckActionPerformed(evt);
            }
        });

        automataBoton.setText("Automata");
        automataBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                automataBotonActionPerformed(evt);
            }
        });

        jLabel3.setText("Posición");

        jLabel5.setText("Nuevo texto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(leerBoton)
                                    .addComponent(derechoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ingresarBotón, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(guardarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(derechaCheck)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(izquierdaCheck)
                                        .addGap(18, 18, 18)
                                        .addComponent(eliminarBoton)
                                        .addGap(18, 18, 18)
                                        .addComponent(editarBoton))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(esSimplificableBoton)
                                .addGap(18, 18, 18)
                                .addComponent(conjuntosBoton)
                                .addGap(18, 18, 18)
                                .addComponent(simplificarBoton)
                                .addGap(108, 108, 108)
                                .addComponent(regularBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(automataBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)))))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(izquierdoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(499, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBoton)
                    .addComponent(leerBoton))
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresarBotón)
                    .addComponent(derechoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(esSimplificableBoton)
                    .addComponent(conjuntosBoton)
                    .addComponent(simplificarBoton)
                    .addComponent(regularBoton)
                    .addComponent(automataBoton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(izquierdaCheck)
                        .addComponent(eliminarBoton)
                        .addComponent(editarBoton))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(derechaCheck)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(izquierdoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(434, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leerBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerBotonActionPerformed
        if(seleccionar.showDialog(null, "Abrir")==JFileChooser.APPROVE_OPTION){
            archivo = seleccionar.getSelectedFile();
            if(archivo.canRead()){
                if(archivo.getName().endsWith("txt")){
                    String documento = this.abrirArchivo(archivo);
                    gramaticaTexto.setText(documento);
                    this.gramatica.reiniciarGramatica();
                    this.gramatica.generarGramaticaFiche(documento);
                    gramaticaTexto.setText(this.gramatica.imprimirGramatica());
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "No se ha seleccionado un archivo txt");
                }
            }
        }
    }//GEN-LAST:event_leerBotonActionPerformed

    private void guardarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBotonActionPerformed
        if (seleccionar.showDialog(null, "Guardar") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionar.getSelectedFile();            
            if (archivo.getName().endsWith("txt")) {
                String Documento = gramaticaTexto.getText();
                String mensaje = this.guardarArchivo(archivo, Documento);
                if (mensaje != null) {
                    JOptionPane.showMessageDialog(null, mensaje);
                } else {
                    JOptionPane.showMessageDialog(null, "No se ha selecciona un archivo txt");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Archivo debe terminar con .txt");
            }        
            gramaticaTexto.setText(gramatica.imprimirGramatica());

        }
    }//GEN-LAST:event_guardarBotonActionPerformed

    private void ingresarBotónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarBotónActionPerformed
        String izquierdo = izquierdoTexto.getText();
        izquierdo = izquierdo.replace(" ", "");
        String derecho = derechoTexto.getText();
        derecho = derecho.replace(" ", "");
        if(izquierdo.equals("")){
            JOptionPane.showMessageDialog(null, "Por favor, rellenar el campo de izquierdo");
            return;
        }
        if(!izquierdo.substring(0,1).equals("<") | !izquierdo.substring(izquierdo.length()-1).equals(">")){
            JOptionPane.showMessageDialog(null, "El lado izquierdo debe ser de la forma <nombre>");
            return;
        }
        gramatica.agregarProduccion(izquierdo, derecho);
        gramaticaTexto.setText(gramatica.imprimirGramatica());
    }//GEN-LAST:event_ingresarBotónActionPerformed

    private void simplificarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simplificarBotonActionPerformed
        if(gramaticaTexto.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se ha ingresado una gramática a evaluar");
            return;
        }
        if(!gramatica.esSimplificable()){
            NTTexto.setText("La gramática no es simplificable");
            return;
        }
        Gramatica aux = gramatica.simplificar();
        this.gramatica = aux;
        gramaticaTexto.setText(gramatica.imprimirGramatica());
    }//GEN-LAST:event_simplificarBotonActionPerformed

    private void regularBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regularBotonActionPerformed
        if(gramaticaTexto.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se ha ingresado una gramática a evaluar");
            return;
        }
        if(gramatica.esRegular()){
            NTTexto.setText("La gramática es regular");
        }
        else{
            NTTexto.setText("La gramática no es regular");
        }
    }//GEN-LAST:event_regularBotonActionPerformed

    private void automataBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_automataBotonActionPerformed
        if(gramaticaTexto.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se ha ingresado una gramática a evaluar");
            return;
        }
        AutomataVista grafica = new AutomataVista();
        grafica.setVisible(true);
    }//GEN-LAST:event_automataBotonActionPerformed

    private void conjuntosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conjuntosBotonActionPerformed
        if(gramaticaTexto.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se ha ingresado un automata a evaluar");
            return;
        }
        ArrayList<String> NTVivos = gramatica.noTerminalesVivos();
        ArrayList<String> NTMuertos = gramatica.noTerminalesMuertos();
        ArrayList<String> NTInalcanzables = gramatica.noTerminalesInalcanzables();
        ArrayList<String> NTAlcanzables = gramatica.noTerminalesAlcanzables();
        
        String texto = "NTVivos: \n"+
                        NTVivos.toString()+"\n"+
                        "NTMuertos: \n"+
                        NTMuertos.toString()+"\n"+
                        "NTInalcanzables: \n"+
                        NTInalcanzables.toString()+"\n"+
                        "NTAlcanzables: \n"+
                        NTAlcanzables.toString()+"\n";
        
        NTTexto.setText(texto);
    }//GEN-LAST:event_conjuntosBotonActionPerformed

    private void derechaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derechaCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_derechaCheckActionPerformed

    private void esSimplificableBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esSimplificableBotonActionPerformed
        if(gramaticaTexto.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se ha ingresado una gramática a evaluar");
            return;
        }
        if(gramatica.esSimplificable()){
            NTTexto.setText("La gramática es simplificable");
        }
        else{
            NTTexto.setText("La gramática no es simplificable");
        }
    }//GEN-LAST:event_esSimplificableBotonActionPerformed

    private void izquierdaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izquierdaCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_izquierdaCheckActionPerformed

    private void eliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBotonActionPerformed
        if(gramaticaTexto.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se ha ingresado una gramática a evaluar");
            return;
        }
        if(posicionTexto.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor, ingresar la posición de la producción que desea eliminar");
            return;
        }
        if(Integer.parseInt(posicionTexto.getText())<0 | Integer.parseInt(posicionTexto.getText())>gramatica.getProducciones().size()){
            JOptionPane.showMessageDialog(null, "Por favor, ingresar una posición válida");
            return;
        }
        gramatica.eliminarProduccion(Integer.parseInt(posicionTexto.getText()));
        gramaticaTexto.setText(gramatica.imprimirGramatica());
    }//GEN-LAST:event_eliminarBotonActionPerformed

    private void editarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBotonActionPerformed
        if (gramaticaTexto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No se ha ingresado una gramática a evaluar");
            return;
        }
        if (posicionTexto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, ingresar la posición de la producción que desea editar");
            return;
        }
        if(Integer.parseInt(posicionTexto.getText())<0 | Integer.parseInt(posicionTexto.getText())>gramatica.getProducciones().size()){
            JOptionPane.showMessageDialog(null, "Por favor, ingresar una posición válida");
            return;
        }
        if ((izquierdaCheck.isSelected() & derechaCheck.isSelected()) | (!izquierdaCheck.isSelected() & !derechaCheck.isSelected())) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccionar que lado de la producción desea editar");
            return;
        }
        if (izquierdaCheck.isSelected()) {
            if (cambioTexto.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Por favor, ingresar un NT de la fomra <NT>");
                return;
            }
            if(!cambioTexto.getText().substring(0, 1).equals("<") | !cambioTexto.getText().substring(cambioTexto.getText().length() - 1).equals(">")){
                JOptionPane.showMessageDialog(null, "Por favor, ingresar un NT de la fomra <NT>");
                return;
            }
        gramatica.modificarGramatica(Integer.parseInt(posicionTexto.getText()), "izquierdo", cambioTexto.getText());
        } else {
            gramatica.modificarGramatica(Integer.parseInt(posicionTexto.getText()), "derecho", cambioTexto.getText());
        }
        gramaticaTexto.setText(gramatica.imprimirGramatica());
    }//GEN-LAST:event_editarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GramaticaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GramaticaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GramaticaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GramaticaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GramaticaVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane NTTexto;
    private javax.swing.JButton automataBoton;
    private javax.swing.JTextPane cambioTexto;
    private javax.swing.JButton conjuntosBoton;
    private javax.swing.JCheckBox derechaCheck;
    private javax.swing.JTextField derechoTexto;
    private javax.swing.JButton editarBoton;
    private javax.swing.JButton eliminarBoton;
    private javax.swing.JButton esSimplificableBoton;
    public static final javax.swing.JTextPane gramaticaTexto = new javax.swing.JTextPane();
    private javax.swing.JButton guardarBoton;
    private javax.swing.JButton ingresarBotón;
    private javax.swing.JCheckBox izquierdaCheck;
    private javax.swing.JTextField izquierdoTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton leerBoton;
    private javax.swing.JTextPane posicionTexto;
    private javax.swing.JButton regularBoton;
    private javax.swing.JButton simplificarBoton;
    // End of variables declaration//GEN-END:variables
}
